services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8081"
    env_file: ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
